### ISSUE TITLE
Improve / Fix Weight Sharing

### ISSUE THREAD

**Issue by shelhamer** [BVLC/caffe#1211]
Weight sharing as-is relies on a weight owner with which shared layers share their parameter blobs. This poses a few problems in relation to loss, loading and saving parameters, and weight initialization that are listed here for addressing.
- [x] Fix incorrect momentum and history due to separation of shared weights #2866  
- [x] Fix the resuming / fine-tuning issue for shared weights; see https://github.com/BVLC/caffe/pull/959#issuecomment-55500404. Done in #594 as it turns out.
- [x] Determine if there is actually a loss / weight ownership issue as asked at https://github.com/BVLC/caffe/pull/546/files#r16817721 by @ashafaei. [No, there is not –shelhamer]
- [x] Save memory through accumulation #1977 by sharing diffs #2866 
- [ ] Load and save only the owned weights and not shared duplicates #2836 for hdf5
- [ ] Figure out how snapshot / restore should resolve by layer or param name and fallback as needed
- [ ] Only the owner should initialize weights. Currently unnecessary work and memory is expended filling all weights, and then these are discarded to share with the weight owners.
- [ ] Die if weight fillers are defined in layers that don't own their parameters (the weights are properly initialized in this case, but only by ignoring the incorrect specification as written).

@jeffdonahue @longjon

**Comment by ruipimenta** [comment]
Hi
Encode and decode layer should share weights but not bias. I tried to implement it but there is a complain:
"Check failed: blob_share_mode_size == num_param_blobs || blob_share_mode_size == 0 Incorrect blob_share_mode size: should be either 0 or the same as the number of the layer's parameter blobs: 2"
Anyone has a sugestion how to avoid this complain? Is there alredy any implementation of decoder layer with shared weights?

thanks

**Comment by shelhamer** [comment]
We should keep #1659 in mind too.

**Comment by j88k** [comment]
Mocha has TiedInnerProductLayer [http://mochajl.readthedocs.org/en/latest/user-guide/layers/computation-layer.html#TiedInnerProductLayer, source: https://github.com/pluskid/Mocha.jl/blob/master/src/layers/tied-inner-product.jl], I guess Caffe could be similar, along the lines of @jeffdonahue suggestion to add a "transposed weights" option to the inner product layer.

**Comment by raingo** [comment]
Do we have an update on these?

Shared weights are very important for recurrent nets.

**Comment by Jim61C** [comment]
Hi, Do we have an update on the 7th problem mentioned above? 

"Only the owner should initialize weights. Currently unnecessary work and memory is expended filling all weights, and then these are discarded to share with the weight owners."

I am currently facing a problem having multiple FC layers sharing weights due to memory issue and I believe that it is due to the fact that even if I share weights between those FC layers, they are still being initialized and take extra memory at the creation of the network, any idea on workaround of this will be greatly appreciated!

Thanks!
