### ISSUE TITLE
Adaptive Solvers: AdaDelta, RMSprop, and ADAM

### ISSUE THREAD

**Issue by shelhamer** [BVLC/caffe#2860]
There are open PRs for adaptive solvers that need review, revision, and merge:

- [x] RMSprop #1890: finished and ready for review in #2867 
- [x] AdaDelta #2782: need to be aligned with the new solver interface #2518 #1977
- [x] ADAM #2856: finished and ready for review in #2918 

As a last step AdaGrad, AdaDelta, and RMSprop could likely be improved by refactoring out shared code into an `AdaptiveSGDSolver`

@ronghanghu these could be good warm-up projects for development.

@longjon @jeffdonahue thoughts on posting tracking issues of this kind? Does this help navigate or is it noise?

**Comment by ronghanghu** [comment]
OK, I'll go through these PRs.

**Comment by matthiasplappert** [comment]
AdaDelta should already conform to the solver interface. Unless I missed something, I ported it over in https://github.com/BVLC/caffe/pull/2782 when merging in master a couple of weeks ago.

**Comment by ronghanghu** [comment]
Since right now these 3 PRs are blocking each other by enum value in SolverType and SolverParameter next available ID, I expect to merge Adam or AdaDelta first, and RMSprop afterwards. I can take over and clean up #2782 or #2856 when necessary. After that, a solver refactor PR can follow addressing the `solver_type` and split `solver.cpp` into different files.

**Comment by ronghanghu** [comment]
Please add one more test case:

* `TestLeastSquaresUpdateWithEverythingAccum` (where you may set kNumIters = 4 and kIterSize = 2 and use CheckAccumulation)

You may take a look at those AdaGradSolverTest for details.

**Comment by ronghanghu** [comment]
Note: #2836 modifies solver as well as introduces new snapshot tests, so a further rebase is needed here. #2870 also introduces new conflicts.

**Comment by bhack** [comment]
@ronghanghu The merging sequence It is becoming to be a "political" issue because there isn't a clear policy for reviews and merges. Fast track merges on younger PR push adaptation work over the older one (apart of the quality, the in shape status, the debasing effort of the older PR)

**Comment by ronghanghu** [comment]
@bhack Indeed, there isn't a clear policy for PR reviewing process right now. Our merge sequence is mainly based on the status of PRs, that is, whether a PR is ready to merge or needs further modification. Since these 2 out of 3 here (Adam and AdaDelta) are still not ready, I expect to wait to merge therm after #2870.

**Comment by bhack** [comment]
The problem is that there isn't almost a rough policy for the community. Readiness it is influenced also by reviews timing other that proposer availability. https://github.com/BVLC/caffe/pull/2836 that brake this was a fast track review. There are many staging PR in the queue that need to support rebasing efforts of fast track Pr merges.

**Comment by ronghanghu** [comment]
Now 2 out of 3 done.

**Comment by ronghanghu** [comment]
Now all of them done. Address solver refactor in #2890.
